cnf(a, axiom, '*'('*'('*'(X, Y), Z), inv('*'(X, Z))) = Y).
cnf(a, axiom, e = '*'(a, inv(a))).
fof(a, conjecture, e = '*'(b, inv(b))).
fof(a, conjecture, ![X]: '*'(e, X) = X).
fof(a, conjecture, ![X]: '*'(X, e) = e).
fof(a, conjecture, ![X]: '*'(inv(X), X) = e).
fof(a, conjecture, ![X]: '*'(X, inv(X)) = e).
fof(a, conjecture, ![X, Y, Z]: '*'('*'(X, Y), Z) = '*'(X, '*'(Y, Z))).
fof(a, conjecture, ![X, Y]: '*'(X, Y) = '*'(Y, X)).
