#!/bin/zsh
typeset -a args

process() {
    for arg in $*; do
        case $arg in
            \"*\")
                process $(echo $arg | cut -c2- | rev | cut -c2- | rev)
                ;;
            @*)
                process $(cat $(echo $arg | cut -c2-))
                ;;
            -lstdc++ | -fuse-ld=gold)
                ;;
            *)
                args+=$arg
                ;;
        esac
    done
}

process $*

exec g++ -static-libgcc -static-libstdc++ $args
